apiVersion: apps/v1
kind: Deployment
metadata:
  name: hepc
  namespace: mrva
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hepc
  template:
    metadata:
      labels:
        app: hepc
    spec:
      containers:
      - name: hepc
        image: mrva-hepc-container:0.4.0
        args:
          - "mc-hepc-serve"
          - "--codeql-db-dir"
          - "db-collection.tmp"
          - "--host"
          - "0.0.0.0"
          - "--port"
          - "8070"
        envFrom:
          - configMapRef:
              name: mrva-config
          - secretRef:
              name: mrva-secrets
        ports:
          - containerPort: 8070
