apiVersion: v1
kind: ConfigMap
metadata:
  name: mrva-config
  namespace: mrva
data:
  POSTGRES_USER: "mrva"
  POSTGRES_DB: "mrvadb"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"

  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_USER: "user"
  RABBITMQ_PORT: "5672"

  MINIO_ROOT_USER: "user"
  MINIO_ENDPOINT: "http://minio:9000"

  MRVA_HEPC_ENDPOINT: "http://hepc:8070"
  MRVA_HEPC_CACHE_DURATION: "60"
  MRVA_HEPC_TOOL: "codeql-javascript"
  MRVA_HEPC_REFROOT: "/refroot/"
  MRVA_HEPC_OUTDIR: "WedMay7"
  MRVA_HEPC_DATAVIACLI: "0"
  MRVA_HEPC_COMMAND: "spigot-cli"

  MRVA_MINIO_VIRTUAL_HOST: "0"
  SERVER_HOST: "server"
  SERVER_PORT: "8080"

  ARTIFACT_MINIO_ENDPOINT: "http://minio:9000"
  QLDB_MINIO_ENDPOINT: "http://minio:9000"
  QLDB_MINIO_ID: "user"
  ARTIFACT_MINIO_ID: "user"
