apiVersion: v1
kind: Secret
metadata:
  name: mrva-secrets
  namespace: mrva
type: Opaque
data:
  POSTGRES_PASSWORD: bXJ2YXBn
  RABBITMQ_PASSWORD: cGFzc3dvcmQ=
  MINIO_ROOT_PASSWORD: bW11c3R5ODQzMg==
