apiVersion: apps/v1
kind: Deployment
metadata:
  name: mrva-server
  namespace: mrva
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mrva-server
  template:
    metadata:
      labels:
        app: mrva-server
    spec:
      containers:
      - name: mrva-server
        image: mrva-server:0.4.0
        args: ["--mode=container", "--loglevel=debug"]
        envFrom:
          - configMapRef:
              name: mrva-config
          - secretRef:
              name: mrva-secrets
        ports:
          - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 3
