apiVersion: apps/v1
kind: Deployment
metadata:
  name: mrva-agent
  namespace: mrva
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mrva-agent
  template:
    metadata:
      labels:
        app: mrva-agent
    spec:
      containers:
      - name: mrva-agent
        image: mrva-agent:0.4.0
        args: ["--loglevel=debug"]
        envFrom:
          - configMapRef:
              name: mrva-config
          - secretRef:
              name: mrva-secrets
        ports:
          - containerPort: 8071
